# Generated by Django 4.1.7 on 2023-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='db',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
